# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3765824d2468b87c4aefe4e0660601ff1a818e5de0c7d9aa78af6e50f8f73e4ed0fd538d2a8ecd788203e3235ae68152ea07a83042ca3b1c9f02a917ea000a1a

test:
  secret_key_base: 323160e0df479a8e2f0692193b889116fdc71a82748caecc498eeef7426c42ab0b9f9f79a55fb376e984d41325fe27eeac79804f412633946cf9c27a36f77998

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
